### ISSUE TITLE
Improve GitHub Actions Workflow Triggers for CI/CD

### ISSUE THREAD

**Issue by akolotov** [blockscout/mcp-server#9]
Currently, our GitHub Actions workflows have the following trigger configurations:

*   **`Build Blockscout MCP Server docker image` (`main.yml`):** Runs on `push` to any branch.
*   **`CI - Run Unit Tests` (`ci.yml`):** Runs on `push` to any branch and on `pull_request` to the `main` branch.
*   **`CI - Run Integration Tests` (`integration-tests.yml`):** Runs only on `workflow_dispatch` (manual trigger).

This configuration leads to the following behavior on Pull Requests:
*   "Build Blockscout MCP Server docker image" runs (due to the push event associated with the PR branch).
*   "CI - Run Unit Tests" runs twice (once for the push to the PR branch, once for the `pull_request` event targeting `main`).

We propose to optimize the workflow triggers to provide a more robust and efficient CI/CD pipeline.

**Desired Workflow Triggers:**

1.  **On Pull Requests (to any branch):**
    *   Run "Build Blockscout MCP Server docker image"
    *   Run "CI - Run Unit Tests"
    *   Run "CI - Run Integration Tests"
2.  **On Push to any branch (excluding `main` for some jobs):**
    *   Run "CI - Run Unit Tests"
3.  **On Push to `main` branch:**
    *   Run "Build Blockscout MCP Server docker image"
    *   Run "CI - Run Unit Tests"
    *   Run "CI - Run Integration Tests"

**Proposed Changes:**

The following modifications should be made to the `.github/workflows/` files:

1.  **`.github/workflows/main.yml` (Build Blockscout MCP Server docker image):**
    *   Change `on: push`
    *   To:
        ```yaml
        on:
          push:
            branches:
              - main
          pull_request:
        ```

2.  **`.github/workflows/ci.yml` (CI - Run Unit Tests):**
    *   Change:
        ```yaml
        on:
          push:
            branches:
              - '**'
          pull_request:
            branches:
              - main
        ```
    *   To:
        ```yaml
        on:
          push:
            branches:
              - '**'
          pull_request: # Will trigger on PRs to any branch
        ```
    *(Note: This will still run on push to `main` due to `branches: ['**']` and on PRs targeting `main`)*

3.  **`.github/workflows/integration-tests.yml` (CI - Run Integration Tests):**
    *   Change `on: workflow_dispatch`
    *   To:
        ```yaml
        on:
          push:
            branches:
              - main
          pull_request:
        ```

**Benefits of these changes:**

*   **Comprehensive PR Validation:** Ensures all critical checks (unit tests, integration tests, Docker build) are performed on Pull Requests before merging.
*   **Faster Feedback on Feature Branches:** Unit tests continue to provide quick feedback for developers on their branches.
*   **Robust `main` Branch:** Guarantees that the `main` branch is always validated with all tests and a successful build.
*   **Reduced Redundancy:** Avoids running the same workflows multiple times for the same event (e.g., unit tests running twice on PRs to main).

**Acceptance Criteria:**

*   GitHub Actions workflows are triggered according to the "Desired Workflow Triggers" section.
*   The `main.yml`, `ci.yml`, and `integration-tests.yml` files are updated as specified.
